import {
  Box,
  Button,
  CssBaseline,
  Grid,
  Modal,
  Paper,
  Stack,
  ThemeProvider,
  Typography,
} from "@mui/material";
import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import { useGlobalCtxt } from "../Components/GlobalContext";
import PannelsComponent from "../Components/Pannels/PannelsComponent";
import IncorrectOptionMessage from "../Components/Quesstions/IncorrectOptionMessage";
import Questions from "../Components/Quesstions/Questions";
import TimeOutModal from "../Components/Quesstions/TimeOutModal";
import theme from "../Components/theme";
import trivial from "../Components/trivial";
import styles from "../styles/Home.module.css";
import { gsap } from "gsap";
import { useRef } from "react";
import CorrectAnswer from "../Components/Quesstions/CorrectAnswer";

export default function Home() {
  const { questionNmbr, incorrectOptions, count, openWrong, isRightAnswer } =
    useGlobalCtxt();
  const currentOptions = trivial[questionNmbr];
  let answers = currentOptions.answers;

  answers.forEach((element) => {
    if (!element.isCorrect) {
      incorrectOptions.push(element.answer);
    }
  });

  const app = useRef();

  return (
    <ThemeProvider theme={theme}>
      <CssBaseline />
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main ref={app} style={{ paddingBlock: "1.5rem" }}>
          <Stack>
            <>
              <PannelsComponent currentOptions={currentOptions} />
              <Questions currentOptions={currentOptions} />
            </>
          </Stack>
          {isRightAnswer ? (
            <CorrectAnswer />
          ) : count === 0 ? (
            <TimeOutModal />
          ) : openWrong === true ? (
            <IncorrectOptionMessage />
          ) : null}
          <CorrectAnswer />
        </main>
      </div>
    </ThemeProvider>
  );
}
